fuseki:
  dcatServiceUri: http://localhost:8080/fuseki/dcat
  adminServiceUri: http://localhost:8080/fuseki/admin
application:
  test: test
---
spring:
    profiles: development
fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin