fuseki:
  dcatServiceUri: http://localhost:8080/fuseki/dcat
  adminServiceUri: http://localhost:8080/fuseki/admin
application:
  crawlerThreadPoolSize: 2
  elasticSearchHost: localhost
  elasticSearchPort: 9300
---
spring:
    profiles: docker
fuseki:
  dcatServiceUri: http://fuseki:8080/fuseki/dcat
  adminServiceUri: http://fuseki:8080/fuseki/admin
application:
  elasticSearchHost: elk
---
spring:
    profiles: development
fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin