version: "2"

services:
  fuseki:
    build: fuseki-test-server
    ports:
     - "3030:8080"
    networks:
      platform:

  server:
    build: dcat-harvester-server
    ports:
     - "8080:8080"
    environment:
     - JAVA_OPTS="-Dspring.profiles.active=docker"
    volumes:
     - ./logs:/usr/local/tomcat/logs:rw
    networks:
      platform:

  elasticsearch:
    build: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      logging:

  logstash:
    build: logstash
    entrypoint: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logs:/usr/local/tomcat/logs:rw
    depends_on:
      - elasticsearch
    networks:
      logging:

  kibana:
    build: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      logging:

networks:
  platform:
  logging:
