fuseki:
  build: fuseki-test-server
  ports:
   - "3030:8080"
   
server:
  build: dcat-harvester-server
  ports:
   - "8080:8080"
  environment:
   - JAVA_OPTS="-Dspring.profiles.active=docker"
  volumes:
   - ./logs:/usr/local/tomcat/logs:rw
  links:
   - fuseki