fuseki:
  build: fuseki-test-server
  ports:
   - "3030:8080"

server:
  build: dcat-harvester-server
  ports:
   - "8080:8080"
  environment:
   - JAVA_OPTS="-Dspring.profiles.active=docker"
  volumes:
   - ./logs:/usr/local/tomcat/logs:rw
  links:
   - fuseki
   - elk

elk:
  build: elk-server
  ports:
    - "5601:5601"
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./logs:/usr/local/tomcat/logs:rw
